select * from  hr_data;

-- OVERALL ATTRITION AND TOTAL EMPLOYEE
SELECT COUNT(CASE WHEN ATTRITION = '1' THEN 1 END) AS ATTRITION_COUNT, COUNT(*) AS TOTAL_EMPLOYEES
FROM HR_data;

-- RELATION BETWEEN  OVERTIME AND ATTRITION COUNT
SELECT OVER_TIME, COUNT(*) AS TOTAL_EMPLOYEES
FROM HR_data
WHERE ATTRITION = 1
GROUP BY OVER_TIME;        /* so employee who are working over time attrition is high for them */

-- OVERALL GENDER DISTRIBUTION IN THE DATASET
SELECT GENDER, COUNT(*) AS TOTAL_EMPLOYEES FROM HR_data 
----where ATTRITION =1
GROUP BY GENDER;               

SELECT GENDER, COUNT(*) AS TOTAL_EMPLOYEES
FROM HR_data
WHERE Attrition = 1
GROUP BY GENDER;

-- RELATION BETWEEN PERFORMANCE RATING AND ATTRITION
SELECT PERFORMANCE_RATING, COUNT(CASE WHEN ATTRITION = '1' THEN 1 END) AS ATTRITION_COUNT
FROM HR_data
GROUP BY Performance_Rating;
-- THERE IS A NEGATIVE CORRELATION BETWEEN THE PERFORMACE RATING AND ATTRITION COUNT


-- RELATION BETWEEN THE PERCENT SALARY HIKE AND ATTRITION COUNT
SELECT PERCENT_SALARY_HIKE, COUNT(*) AS ATTRITION_COUNT
FROM HR_DATA
WHERE ATTRITION = 1
GROUP BY  Percent_Salary_Hike
ORDER BY ATTRITION_COUNT DESC;
-- THERE IS A NEGATIVE CORRELATION BETWEEN THE PERCENT SALARY HIKE AND ATTRITION COUNT


-- RELATION BETWEEM YEARS IN CURRENT ROLE AND ATTRITION COUNT
SELECT Years_In_Current_Role, COUNT(CASE WHEN ATTRITION = '1' THEN 1 END) AS ATTRITION_COUNT
FROM HR_DATA
WHERE Years_In_Current_Role > (SELECT AVG(YEARS_IN_CURRENT_ROLE) FROM HR_DATA)
GROUP BY Years_In_Current_Role
ORDER BY Years_In_Current_Role;
-- EMPLOYEES WHO ARE WORKING IN THE COMPANY FROM LAST 5-10 YEARS ARE HAVING THE HIGHEST ATTRITION COUNT

-- EMPLOYEE ATTRITION BASED ON THE AGE RANGE
SELECT CASE WHEN AGE <= 29 THEN '18-29'
            WHEN AGE >= 30 AND AGE <= 39 THEN '30-39'
			WHEN AGE >= 40 AND AGE <= 49 THEN '40-49'
			WHEN AGE >= 50 AND AGE <= 59 THEN '50-59'
			ELSE '60 OR OLDER'
			END AS 'AGE RANGE',
			COUNT(*) AS 'NUMBER OF ATTRITION COUNT BASED ON AGE RANGE'
FROM HR_data
WHERE ATTRITION = 1 AND Years_At_Company >= 2
GROUP BY CASE WHEN AGE <= 29 THEN '18-29'
            WHEN AGE >= 30 AND AGE <= 39 THEN '30-39'
			WHEN AGE >= 40 AND AGE <= 49 THEN '40-49'
			WHEN AGE >= 50 AND AGE <= 59 THEN '50-59'
			ELSE '60 OR OLDER'
			END
ORDER BY [AGE RANGE];
-- AGE GROUP OF '18-29' AND '30-39' HAVE THE MAXIMUM ATTRITION COUNTS FOR THOSE EMPLOYEES WHO HAVE BEEN WORKING IN THE COMPANY FROM LAST 1 

SELECT * FROM HR_data;

SELECT DISTINCT DEPARTMENT FROM HR_data;

-- DEPARTMENT WISE ATTRITION COUNT
SELECT DEPARTMENT, COUNT(*) AS ATTRITION_COUNT
FROM HR_data
WHERE Attrition = 1
GROUP BY Department
ORDER BY ATTRITION_COUNT DESC;
-- R&D AND SALES DEPARTMENT ARE HAVING THE MAX ATTRITION WITH ALMOST 95%

-- ENVIRONMENT SATISFACTION, JOB SATISFACTION AND RELATIONSHIP SATISFACTION ON ATTRITION COUNTS
SELECT ENVIRONMENT_SATISFACTION, COUNT(*) AS ATTRITION_COUNTS
FROM HR_data
WHERE ATTRITION = 1
GROUP BY ENVIRONMENT_SATISFACTION
ORDER BY ATTRITION_COUNTS DESC;
-- THERE IS NO CORRELATION BETWEEN THE ENVIRONMENT SATISFACTION AND ATTRITION COUNTS

SELECT JOB_SATISFACTION, COUNT(*) AS ATTRITION_COUNTS
FROM HR_data
WHERE ATTRITION = 1
GROUP BY JOB_SATISFACTION
ORDER BY ATTRITION_COUNTS DESC;
-- THERE IS NO CORRELATION BETWEEN THE JOB SATISFACTION AND ATTRITION COUNTS


SELECT RELATIONSHIP_SATISFACTION, COUNT(*) AS ATTRITION_COUNTS
FROM HR_data
WHERE ATTRITION = 1
GROUP BY RELATIONSHIP_SATISFACTION
ORDER BY ATTRITION_COUNTS DESC;
-- THERE IS NO CORRELATION BETWEEN THE RELATIONSIP SATISFACTION AND ATTRITION COUNTS

-- WORK LIFE BALANCE AND ATTRITION COUNTS
SELECT WORK_LIFE_BALANCE, COUNT(*) AS ATTRITION_COUNTS
FROM HR_data
WHERE Attrition = 1
GROUP BY Work_Life_Balance
ORDER BY ATTRITION_COUNTS DESC;
-- THERE IS NO RELATION BETWEEN THE WORK LIFE BALANCE AND ATTRITION COUNTS

-- DISTANCE FROM HOME AND ATTRITION COUNTS
select distance_from_home, count(*) as attr_count
from HR_data
where attrition = 1
group by distance_from_home
order by Distance_From_Home desc, attr_count desc;
-- THERE IS NO RELATION BETWEEN DISTANCE FROM HOME AND ATTRITION COUNTS
